let suggestions = [
    "Kanawa",
    "Bonawa",
    "Hodanawa",
    "Wadinawa",
    "Pihadanawa",
    "YouTube Channel",
    "Adarei",
    "Tharahai",
    "Narakai",
    "Hodai",
    "Athu ganawa",
    "Nanawa",
    "Muna hodanawa",
    "Oluwa piranawa",
    "Yanawa",
    "Enawa",
    "Hitawanawa",
    "Wathura ihanawa",
    "Uyanwa",
    "Badinawa",
    "Issarahata yanna",
    "Passata yanna",
    "Wamata yanna",
    "Dakunata yanna",
    "Beheth bonna",
    "Kawanna",
    "Powanna",
    "Naawanna",
    "Adinna",
    "Kasanna",

    "Nawathwanna",
    "Idiriyata",
    "Pasugami",
    "Wama",
    "Dakuna",
    "Itha Hodai",
    "Itha Narakai",
];